name: bobibot
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"  # Utilisation de Dart SDK 2.18.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1  # Update to a version compatible with cloud_firestore
  firebase_auth: ^4.0.0   # Ensure compatibility with firebase_core ^2.x.x
  cloud_firestore: ^4.10.0 # Update to a version compatible with firebase_core ^2.x.x
  http: ^0.13.3
  shared_preferences: ^2.1.0
  onesignal_flutter: ^3.2.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.0
  flutter_local_notifications: ^14.0.0+1
  timezone: ^0.9.2
  permission_handler: ^10.4.0
  uuid: ^3.0.7
  logger: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0  # Version compatible avec Dart 2.18.0

flutter:
  uses-material-design: true